services:
  - type: web
    name: bahith-al-suwar
    env: python
    buildCommand: |
      pip install -r requirements.txt && \
      wget -O chromium.zip "https://s3.eu-north-1.amazonaws.com/chromium.file/chromium.zip" && \
      unzip -o chromium.zip -d /tmp/chromium/ && \
      wget -O user_data.zip "https://s3.eu-north-1.amazonaws.com/chromium.file/userdata/user_data.zip" && \
      unzip -o user_data.zip -d /tmp/
    startCommand: gunicorn app:app
    envVars:
      - key: USER_DATA_PATH
        value: /tmp/user_data
      - key: USER_DATA_DASH_PATH
        value: /tmp/user-data
      - key: YESCAPTCHA_EXTENSION_PATH
        value: /tmp/yescaptcha-extension
      - key: PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH
        value: /tmp/chromium/chrome-linux/chrome
      - key: IMGBB_API_KEY
        value: 8a0183d939bb1db66e0e505b80c758e6
    autoDeploy: true
