"""phase2: provider_calls, phash columns, nullable user_id

Revision ID: 7fb8906f1f44
Revises: a32baf980004
Create Date: 2026-07-29 16:02:42.834352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fb8906f1f44'
down_revision = 'a32baf980004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_calls_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_calls_ok'), ['ok'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_calls_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_calls_status_code'), ['status_code'], unique=False)

    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_phash', sa.String(length=32), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_analyses_media_phash'), ['media_phash'], unique=False)

    with op.batch_alter_table('searches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_phash', sa.String(length=32), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_searches_image_phash'), ['image_phash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('searches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_searches_image_phash'))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('image_phash')

    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_media_phash'))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('media_phash')

    with op.batch_alter_table('provider_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_calls_status_code'))
        batch_op.drop_index(batch_op.f('ix_provider_calls_provider'))
        batch_op.drop_index(batch_op.f('ix_provider_calls_ok'))
        batch_op.drop_index(batch_op.f('ix_provider_calls_created_at'))

    op.drop_table('provider_calls')
    # ### end Alembic commands ###
