"""baseline: full schema

Revision ID: a32baf980004
Revises: 
Create Date: 2026-07-23 17:53:06.971877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a32baf980004'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Databases created before Alembic (db.create_all era) already have the
    # full schema. Skip creation; Alembic still records this revision, which
    # is exactly the desired "stamp head" behavior for existing deployments.
    bind = op.get_bind()
    if sa.inspect(bind).has_table('users'):
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_countries_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_countries_is_active'), ['is_active'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_admin'), ['is_admin'], unique=False)

    op.create_table('analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_type', sa.String(length=30), nullable=False),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('media_hash', sa.String(length=64), nullable=True),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=True),
    sa.Column('confidence_ai', sa.Float(), nullable=True),
    sa.Column('confidence_human', sa.Float(), nullable=True),
    sa.Column('verdict', sa.String(length=100), nullable=True),
    sa.Column('generator', sa.String(length=100), nullable=True),
    sa.Column('detailed_results', sa.JSON(), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_analysis_type'), ['analysis_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_is_ai_generated'), ['is_ai_generated'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_media_hash'), ['media_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_service'), ['service'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_user_id'), ['user_id'], unique=False)

    op.create_table('keywords',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'keyword', name='uq_user_keyword')
    )
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keywords_user_id'), ['user_id'], unique=False)

    op.create_table('searches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('search_type', sa.String(length=30), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('image_hash', sa.String(length=64), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('searches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_searches_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_searches_image_hash'), ['image_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_searches_search_type'), ['search_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_searches_user_id'), ['user_id'], unique=False)

    op.create_table('sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('country_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_country_id'), ['country_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_domain'), ['domain'], unique=True)
        batch_op.create_index(batch_op.f('ix_sources_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_is_verified'), ['is_verified'], unique=False)

    op.create_table('user_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_feature', sa.String(length=50), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_files_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_files_file_type'), ['file_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_files_user_id'), ['user_id'], unique=False)

    op.create_table('analysis_frames',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('timestamp_seconds', sa.Float(), nullable=False),
    sa.Column('frame_url', sa.String(length=500), nullable=True),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('detection_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_frames', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_frames_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('search_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('search_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_results_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_results_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_results_search_id'), ['search_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_results_source_id'), ['source_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_results_source_id'))
        batch_op.drop_index(batch_op.f('ix_search_results_search_id'))
        batch_op.drop_index(batch_op.f('ix_search_results_published_at'))
        batch_op.drop_index(batch_op.f('ix_search_results_domain'))

    op.drop_table('search_results')
    with op.batch_alter_table('analysis_frames', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_frames_analysis_id'))

    op.drop_table('analysis_frames')
    with op.batch_alter_table('user_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_files_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_files_file_type'))
        batch_op.drop_index(batch_op.f('ix_user_files_created_at'))

    op.drop_table('user_files')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_is_verified'))
        batch_op.drop_index(batch_op.f('ix_sources_is_active'))
        batch_op.drop_index(batch_op.f('ix_sources_domain'))
        batch_op.drop_index(batch_op.f('ix_sources_country_id'))
        batch_op.drop_index(batch_op.f('ix_sources_category'))

    op.drop_table('sources')
    with op.batch_alter_table('searches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_searches_user_id'))
        batch_op.drop_index(batch_op.f('ix_searches_search_type'))
        batch_op.drop_index(batch_op.f('ix_searches_image_hash'))
        batch_op.drop_index(batch_op.f('ix_searches_created_at'))

    op.drop_table('searches')
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keywords_user_id'))

    op.drop_table('keywords')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_user_id'))
        batch_op.drop_index(batch_op.f('ix_analyses_service'))
        batch_op.drop_index(batch_op.f('ix_analyses_media_hash'))
        batch_op.drop_index(batch_op.f('ix_analyses_is_ai_generated'))
        batch_op.drop_index(batch_op.f('ix_analyses_created_at'))
        batch_op.drop_index(batch_op.f('ix_analyses_analysis_type'))

    op.drop_table('analyses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_is_admin'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_countries_is_active'))
        batch_op.drop_index(batch_op.f('ix_countries_code'))

    op.drop_table('countries')
    # ### end Alembic commands ###
