"""phase3: image_vectors internal provenance index

Revision ID: adde0a044e1e
Revises: 7fb8906f1f44
Create Date: 2026-07-29 20:09:38.564377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adde0a044e1e'
down_revision = '7fb8906f1f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_vectors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('media_hash', sa.String(length=64), nullable=False),
    sa.Column('phash', sa.String(length=32), nullable=True),
    sa.Column('dhash', sa.String(length=32), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('dim', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('ref_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('image_vectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_vectors_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_vectors_media_hash'), ['media_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_image_vectors_phash'), ['phash'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_vectors_source'), ['source'], unique=False)

    # pgvector fast path — Postgres only (SQLite dev uses the JSON column).
    # Requires the pgvector extension, available on Render Postgres.
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        try:
            op.execute('CREATE EXTENSION IF NOT EXISTS vector')
            op.execute('ALTER TABLE image_vectors '
                       'ADD COLUMN embedding_vec vector(384)')
            op.execute('CREATE INDEX ix_image_vectors_embedding_vec '
                       'ON image_vectors USING ivfflat '
                       '(embedding_vec vector_cosine_ops) WITH (lists = 100)')
        except Exception:
            # extension unavailable on this Postgres — JSON fallback still works
            pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_vectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_vectors_source'))
        batch_op.drop_index(batch_op.f('ix_image_vectors_phash'))
        batch_op.drop_index(batch_op.f('ix_image_vectors_media_hash'))
        batch_op.drop_index(batch_op.f('ix_image_vectors_created_at'))

    op.drop_table('image_vectors')
    # ### end Alembic commands ###
